apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-service-deployment
  labels:
    app: caching-service
    environment: production
    version: SEMVER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caching-service
  template:
    metadata:
      labels:
        app: caching-service
        version: SEMVER
    spec:
      serviceAccountName: caching-service-sa
      containers:
      - name: caching-service
        image: docker:5000/caching-service:SEMVER
        resources:
          requests: 3Gi
          limits:
            memory: 4Gi
          ephemeral-storage: 2Gi
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: ephemeral
            mountPath: "/tmp"